### ISSUE TITLE
ERROR: Error: image kinetic/nutch:latest not found

### ISSUE THREAD

**Issue by jvence** [tpickett/mongo-elasticsearch-nutch#2]
Running 'docker-compose up' fails with:
ERROR: Error: image kinetic/nutch:latest not found

**Comment by jvence** [comment]
Replacing kinetic/nutch with apache/nutch doesn't work as the nutch image is not loaded when using: 'docker-compose up'

**Comment by tpickett** [comment]
sorry for the late response, I haven't used this image in a while. Ill fire it up and see what is going on.

**Comment by mebinjacob** [comment]
replace it with tpickett/nutch, that works, plus if you are using it on windows, then the volume doesn't load by default cause of a known issue with docker. I had to do '`docker volume create mongo`' and then the following docker-compose.yml worked for me.

```
nutch:
  image: tpickett/nutch
  ports:
    - "8083:8080"
    - "8084:8081"
  links:
    - "mongoNutch:mongo"
    - "elasticsearchNutch:elasticsearch"
  environment:
    - SEEDLIST="http://reddit.com/r/node/"
mongoNutch:
  image: mongo
  ports:
    - "27020:27017"
  volumes:
    - "mongo:/data/db"
elasticsearchNutch:
  image: elasticsearch:1.4
  ports:
    - "9200:9200"
    - "9300:9300"
```
